- components/helpers/heading/index.js
- components/hoc/withData/error.md
- components/hoc/withData/index.js
- components/hoc/withData/loading.md
- components/hoc/withData/withData.md
- components/image/image.js
- components/rawHTML/index.js
- config/styleguide.config.js
- reducers/index.js
- sagas/index.js
- styleguide/components/wrapper.js
- Also add examples, set up sagas for styleguide
- Fix saga for componentData to allow multiple components on the same page
> Set withData to provide data in a prop corresponding to componentName

- server/bustCache.js
- server/bustPageCache.js
- server/bustPurgePageCache.js
- server/index.js
- server/purgePageCache.js
closes #89 
Purging the Redis cache when a PURGE request is made on Irving.
> Clearing redis cache on PURGE request

- config/webpack/env.js
- server/serverRenderer.js
- utils/addTrailingSlash.js
- utils/addTrailingSlash.test.js
- utils/getRelativeUrl.js
- utils/getRelativeUrl.test.js
- Add general support for CONFIG_ env vars
[**IRV-166**](https://alleyinteractive.atlassian.net/browse/IRV-166)
> Add `CONFIG_FORCE_TRAILING_SLASHES` env var and integrate with `getRelativeUrl.js`

- packages/integrations/components/googleTagManager/index.js
> Update GTM component with dataLayer, custom trigger support

- package-lock.json
- package.json
- packages/core/README.md
- packages/core/package.json
- packages/vip-go/README.md
- packages/vip-go/package.json
- packages/vip-go/services/monitorService.js
This PR will:
* Address issue with `monitorService` to anticipate possibility `vip-go` package will return `undefined` when attempting to instantiate `newrelic`.
* Update READMEs with `.env` var information
* Update `ioredis` and `newrelic` packages
* Fix audit
> Further fixes for vip go package

- packages/styled-components/babel.config.js
- packages/styled-components/components/grid/cell.js
- packages/styled-components/components/grid/cellStyles.js
- packages/styled-components/components/grid/container.js
- packages/styled-components/components/grid/container.md
- packages/styled-components/components/grid/containerStyles.js
- packages/styled-components/components/grid/gridProvider.js
- packages/styled-components/components/grid/index.js
Add `<GridProvider />` to styled components package
> Grid provider

- .travis.yml
- package-lock.json
- package.json
- packages/core/test/irving-test.config.js
- packages/core/utils/toReactElement.js
- packages/core/utils/toReactElement.test.js
* add functionality and support for component groups
* add test suite to toReactElement
* change install scripts to bootstrap to prevent issues with initial npm install
* add --parallel flag to test:watch
> Component groups

- .travis.yml
- packages/core/README.md
- packages/core/cli/start.js
- packages/core/components/helpers/link/index.js
- packages/core/config/irvingConfigSchema.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/services/fetchComponentData.js
- packages/core/services/fetchComponents.js
- packages/core/test/irving-test.config.js
- packages/core/utils/addTrailingSlash.js
- packages/core/utils/getRelativeUrl.js
- packages/core/utils/getRelativeUrl.test.js
This PR will:
* Fix issue with `getRelativeUrl` function erroneously removing protocols like `mailto:`
* Add support for creating passthrough proxies directly in your `irving.config.server.js` file
> Url Updates

- packages/core/hooks/useLoadScript.js
- Move option defaults into destructuring statement to ensure they're set properly
> Switch to using more generic attrs option

- packages/core/README.md
- packages/core/config/irvingConfigSchema.js
- packages/core/config/readme.md
- packages/core/config/webpack/env.js
- packages/core/selectors/getCookies.js
- packages/core/utils/addTrailingSlash.js
- packages/vip-go/index.js
- packages/vip-go/irving.config.js
- packages/vip-go/package.json
[**IRV-256**](https://alleyinteractive.atlassian.net/browse/IRV-256)
> Add logic to configure blacklist for trailing slash logic

- packages/core/utils/createComponentDataKey.test.js
This PR adds tests to createComponentDataKey
this is part of PD work -- getting comfortable with test writing, improving my JS skills, and learning about the inner workings of Irving :-)
> add test to createComponentDataKey

- packages/core/services/readme.md
Updating some broken, out of date, links.
> Updating some links

- packages/integrations/components/disqus/index.js
- packages/integrations/components/googleTagManager/index.js
ticket: https://alleyinteractive.atlassian.net/browse/IRV-294
> IRV-294 Fix duplicate script tag issue in gtm component

- packages/vip-go/package-lock.json
- packages/vip-go/package.json
- packages/vip-go/services/cacheService.js
Update VIP Go packages and include new redis/cache service
> Vip package update

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/server/bustPageCache.test.js
- packages/core/services/fetchComponents.js
- packages/core/services/fetchComponents.test.js
- packages/core/services/utils/createComponentsEndpointQueryString.js
- packages/core/services/utils/createComponentsEndpointQueryString.test.js
- packages/core/services/utils/getExtraQueryParams.js
Further updates to the work from https://github.com/alleyinteractive/irving/pull/141 based on the review after the PR was merged.
> Cache test improvements

- packages/core/reducers/errorReducer.test.js
[https://alleyinteractive.atlassian.net/browse/PDACG-1538](https://alleyinteractive.atlassian.net/browse/PDACG-1538)
> Add test suite for errorReducer reducer

- packages/core/components/hoc/withData/getRequestUrl.js
- packages/core/components/hoc/withData/getRequestUrl.md
- packages/core/components/hoc/withData/getRequestUrl.test.js
Refactoring and adding tests for the `getRequestUrl` function.
> getRequestUrl Improvements

- packages/core/package-lock.json
- packages/core/package.json
IRV-279
Somehow I removed the `@irvingjs/babel-preset-irving` dependency in the core package. This PR will add that back in.
Tested on client project
> fix missing dependency for irving babel preset in core

- packages/core/components/hoc/withLoader.md
https://alleyinteractive.atlassian.net/browse/IRV-271
Document the options for `loadingProps` in withLoader.md
it's docs
> IRV-271 - update docs for withLoader HOC to reflect recent updates

- packages/core/cli/start.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/server/auth.js
- packages/core/server/cache.js
- packages/core/server/customizeRedirect.js
- packages/core/server/purgeCache.js
N/A
* Require basic auth to access `/cache-keys` endpoint
* Require basic auth or the appropriate origin for the `/purge-cache` endpoint
* Add some logging to the `purgeCache` method
Tested on locally and on staging.
> Cache protection

- packages/core/config/webpack/plugins.js
- packages/core/utils/getConfigField.js
- packages/styled/index.js
- packages/vip-go/index.js
N/A
Solve a problem where we were defining and referencing a `BUILD` variable in our project's Travis config that was interfering with this `BUILD` variable. As a result, we were seeing an error `Cannot find module '@irvingjs/irving.config'`. Renaming this var fixes the issue.
Tested in the irving-dev environment
> Rename BUILD to WEBPACK_BUILD

- PUBLISHING.md
N/A
Fix some minor typos in publishing instructions
It's docs
> Fix some minor typos in publishing instructions

- packages/core/server/getCacheKeys.js
- packages/core/server/purgeCache.js
- packages/core/services/cacheService/defaultService.js
- packages/core/services/fetchComponentData.js
- packages/core/services/fetchComponents.js
Cache stampede
Fix errors occurring in cache endpoints if cache client isn't configured.
Tested on irving dev
> Cache client fix

- packages/styled-components/components/socialSharing/index.js
- packages/styled-components/components/socialSharing/socialSharingItem.js
- packages/styled-components/components/socialSharing/themes/default.js
- packages/styled-components/index.js
- packages/styled-components/package.json
[IRV-407](https://alleyinteractive.atlassian.net/browse/IRV-407)
Adds social sharing component to styled components packages
Tested in irving-example theme
> IRV-407 social sharing

- .gitignore
- .storybook/README.md
- .storybook/main.js
- package.json
- packages/styled-components/components/byline/byline.stories.js
- packages/styled-components/components/container/container.stories.js
- packages/styled-components/components/fragment/fragment.stories.js
- packages/styled-components/components/link/link.stories.js
- packages/styled-components/components/logo/logo.stories.js
- packages/styled-components/components/menu/menu.stories.js
- packages/styled-components/components/pagination/pagination.stories.js
- packages/styled-components/components/socialSharing/socialSharing.stories.js
- packages/styled-components/components/text/text.stories.js
- stories/00-intro/00-Intro.stories.mdx
- stories/01-project-setup/00-Project-Setup.stories.mdx
Implements the decisions made in the [documentation RFC in Basecamp](https://3.basecamp.com/4209995/buckets/15866357/messages/2774157602).
Update the Storybook to be applicable for all of Irving's documentation.
It builds locally and has already been pushed up to [storybook.irvingjs.com](http://storybook.irvingjs.com).
> docs(storybook): modify Storybook setup to be applicable for all of Irving's documentation

- packages/styled-components/index.js
- packages/styled-components/package-lock.json
- packages/styled-components/package.json
Implements a sane default for CSS grid.
Allow developers to use the `styled-css-grid` easily.
> feat(adds a css grid solution.): adds a sane default/option for developers wanting to use CSS Grid

- packages/styled-components/components/image/image.stories.js
- packages/styled-components/components/image/index.js
- packages/styled-components/components/image/themes/default.js
- packages/styled-components/index.js
- packages/styled-components/package-lock.json
- packages/styled-components/package.json
Jira's [IRV-475](https://alleyinteractive.atlassian.net/browse/IRV-475).
Implement the first Image alpha component, derived from the `@irvingjs/styled/components/image`.
Tested locally and documented in Storybook.
> feat(image component.): implement the first alpha of an Image component

- packages/core/package-lock.json
- packages/core/package.json
- packages/styled-components/components/byline/index.js
- packages/styled-components/components/container/index.js
- packages/styled-components/components/image/index.js
- packages/styled-components/components/image/themes/default.js
- packages/styled-components/components/socialSharing/index.js
- packages/styled-components/components/socialSharing/socialSharingItem.js
- packages/styled-components/package-lock.json
- packages/styled-components/package.json
None.
Resolves some recent linter issues.
> ESLint fixes

- packages/core/components/app/index.js
- packages/core/components/helpers/spinner/index.js
- packages/core/components/image/image.js
- packages/core/components/placeholder/index.js
- packages/core/services/cacheService/getClient.js
- packages/core/services/cacheService/getRedisOptions.js
- packages/core/services/cacheService/getRedisOptions.test.js
- packages/core/services/cacheService/isRedisUrl.js
N/A
* Fix functionality for setting up redis using a url with a `redis://` protocol
I've tested it on a client staging site
> Redis protocol fix

- packages/styled-components/components/text/index.js
Hotfix.
Fix the responsiveEmbed theme in the `irving/text` component.
Fixed locally.
> fix(text component theme): fix the include for responsiveEmbed

- packages/styled-components/index.js
None
Fixes the siteThemeProvider import in the `styled-components` package to use the correct case.
> fix(fix the sitethemeprovider import being case-sensitie): update siteThemeProvider import case

- .storybook/main.js
- package-lock.json
- package.json
Doesn't directly close an issue but will facilitate work to refine components in the Styled Components package
Add the Storybook a11y addon
Tested locally -- see screenshot
> Add Storybook a11y addon 

- .storybook/README.md
None.
Add additional info about Surge for contributors.
No code, just docs.
> Add details about Surge to the docs.

- package-lock.json
- package.json
Fixes an error when running storybook that `@storybook/addon-a11y` wasn't found.
Ensure the package is installed.
Tested locally
> fix(storybook docs): ensure the a11y package is installed

- packages/styled-components/package-lock.json
- stories/03-wordpress/02-Templating.stories.mdx
- stories/03-wordpress/03-Components.stories.mdx
not applicable
provide documentation to developers new to Irving
not applicable
> IRV-589/ Storybook-Templating-Components docs: add content to WordPress sections: templating and components

- stories/04-hosting/05-WordPress-VIP.stories.mdx
Fixes the table of contents for VIP docs.
> Fix table of contents

- packages/styled-components/index.js
Fix the mapping for components from camel case to dash.
> Fix component mapping

- packages/integrations/components/pico/index.js
IRV-526
Add better proptypes and clarify the pageInfo values.
Confirmed locally.
> Add better data handling

- packages/integrations/components/coral/index.js
- packages/integrations/components/coral/readme.md
See alleyinteractive/wp-irving#222 for relevant WP component files.
> IRV-643: allow embed to render from JSON template

- packages/styled-components/components/bodyWrapper/index.js
- packages/styled-components/components/logo/index.js
- packages/styled-components/components/logo/themes/default.js
- packages/styled/utils/index.js
- packages/styled/utils/siteTheme.js
N/A
* Modify the logo component to support children (used for an SVG logo in this case)
* Add `siteTheme` helper function
Tested on client project
> Styled component updates

- packages/styled-components/components/pagination/index.js
None
Ensure that if no query string is present, the pagination URL does not include a trailing question mark
Tested on client project
> Fix pagination URL in pagination component

- .github/workflows/push.yml
- packages/styled-components/components/container/index.js
None.
* Add support for passing in a `className` prop to be applied to the container wrapper.
* Add alpha release GH action
Tested in client project.
> Add support for className on the container component

- packages/styled-components/components/image/index.js
This is a follow up of IRV-506 that fixes some eslint related bugs with the irving/image component
introduced in 6b2aeb1.
> fix(image): Fix eslint errors introduced in merge of #278

- packages/styled-components/components/pagination/index.js
None.
Ensure that query vars are maintained while paginating.
> Fix the query string handling for the pagination component

- packages/integrations/reducers/coralReducer.js
- packages/integrations/selectors/coralSelector.js
> DEF-246: Update reducer for username selection behavior

- packages/integrations/components/coral/withPico.js
- packages/integrations/components/googleTagManager/index.js
- packages/integrations/sagas/gtmSaga.js
- packages/integrations/sagas/index.js
- Adds default data layer to GTM component
- Adds Coral events for GTM
- Adds Pico events for GTM
> DEF-36: Add GTM events for Coral and Pico integrations

- packages/styled-components/components/socialSharing/index.js
Hotfix for bug in https://github.com/alleyinteractive/irving/pull/301
> HOTFIX: Target not defined, destructure

- packages/styled-components/components/socialSharing/index.js
Update 4.0 release with contents of https://github.com/alleyinteractive/irving/pull/304
> Hotfix social target

- PUBLISHING.md
- packages/styled-components/components/link/index.js
- packages/styled-components/components/link/themes/default.js
- packages/styled-components/components/pagination/index.js
- packages/styled-components/components/searchForm/index.js
- packages/styled-components/components/socialLinks/index.js
- packages/styled-components/components/socialSharing/index.js
Adds data attributes that can be listened for using Google Tag Manager.
> DEF-36: Add GTM event attributes

- packages/integrations/sagas/picoSaga.js
> fix(pico): add safety check to visit action

- packages/integrations/components/pico/index.js
- packages/integrations/sagas/picoSaga.js
DEF-289
This fixes an issue where visits were being triggered before new Pico data had been updated and
ensures that we always pass a true article value whenever we are on a post.
> fix(pico): Fix pageview data not being updated properly

- packages/integrations/components/pico/utils.js
> fix(pico): mount signup form node at root

- packages/integrations/components/pico/utils.js
> hotfix(pico): mount payment management node

- packages/integrations/components/pico/index.js
This reverts part of the change in 86130c3.
> fix(pico): Reinsert initialization process

- .travis.yml
- packages/integrations/components/pico/index.js
- packages/integrations/sagas/picoSaga.js
> Bring Pico integration updates into release/4.1

- CHANGELOG.md
- lerna.json
- packages/integrations/CHANGELOG.md
- packages/integrations/components/pico/utils.js
- packages/integrations/package-lock.json
- packages/integrations/package.json
> fix(release/4.1.0)

- packages/integrations/components/pico/index.js
> fix(pico): poll for widget existence in effect

- packages/core/reducers/providersReducer.js
- packages/integrations/components/pico/index.js
- packages/integrations/components/pico/usePollForNode.js
N/A
* Create `usePollForNode` hook.
* Modify polling functionality to use a different state determining if the node has been found—`null` if not found, the DOM node itself if found.
Needs to be tested on develop
> Abstract node polling functionality and modify it slightly

- packages/integrations/components/googleTagManager/index.js
This ensures the dataLayer is serialized inside the inline script to avoid URL based XSS attacks.
IRV-768
> fix(gtm): fix XSS issue in GTM

- packages/integrations/components/googleTagManager/index.js
This back-ports fix 3731639 from the master to the 4.1 branch
See #363.
> Backport #363 to the 4.1 branch

- packages/styled-components/components/byline/index.js
N/A
* Wrap each delimiter in a span if it isn't already
* Add classes so that each piece can be targeted for styling
Tested locally
> feat(byline): ensure all delimiter text is wrapped with spans with classes

- packages/core/services/fetchComponents.js
None.
Add log output for when the components endpoint aborts.
> feat(logging): add error log for component endpoint aborts

- README.md
None.
Update readme to point towards the Storybook docs.
Just readme.
> Update readme to point towards Storybook

- stories/08-integrations/03-Supported-Wordpress-Plugins.stories.mdx
https://github.com/alleyinteractive/wp-irving/pull/284
Remove docs about having to manually add the `<link rel="amphtml" href="..." />` tag now that it's automated.
Docs only.
> Update integrations docs for AMP

- packages/wordpress/blockEditor.js
- packages/wordpress/config/webpack.config.multi.js
- packages/wordpress/package.json
N/A
* Fix siteTheme functionality for editor styles in wp-admin
tested on client site
> Editor sitetheme fix

- .github/PULL_REQUEST_TEMPLATE.md
- .storybook/README.md
- .travis.yml
- CONTRIBUTING.md
- bin/deploy.sh
- lerna.json
- package.json
- stories/00-intro/05-Contributing.stories.mdx
- stories/06-styling/02-css-modules-and-postcss.stories.mdx
- stories/06-styling/03-styled-components.stories.mdx
- stories/07-site-theme/01-site-theme-provider.stories.mdx
- stories/08-integrations/01-Integrations-Manager.stories.mdx
- stories/08-integrations/03-Supported-Wordpress-Plugins.stories.mdx
- stories/10-packages/00-Overview.stories.mdx
- stories/10-packages/01-Creating-a-Package.stories.mdx
- stories/12-concepts/03-State-Management.stories.mdx
- stories/12-concepts/05-Core-Package-Structure.stories.mdx
prepares code for switching the `master` branch to `main`
> docs: remove instances of master

- packages/styled-components/components/socialSharing/index.js
N/A
Address a bug in the Social Sharing component that was causing platforms to display in the default platform order, instead of the passed platform order
Tested in client project
> Fix bug causing order of icons to not be respected

- packages/core/config/html.js
N/A
Allow `button` tags to be rendered by components utilizing the `richText` config for sanitization.
Tested on a client project
> fix(html): add button to list of allowed tags

- packages/core/hooks/useClientNavigationOnClick.js
> IRV-828: explicitly call open on ctrl/metaKey click

- packages/integrations/components/coral/index.js
Reviewed in https://github.com/alleyinteractive/irving/pull/393
> HOTFIX: Remove Coral embeds to prevent side effect buildup

- packages/core/hooks/useClientNavigationOnClick.js
> fix: remove window event bubble

- packages/styled-components/components/link/index.js
> LEDE-535: exit click handler early to enable command+click tab opening

- packages/core/config/html.js
N/A
Ensure link tags aren't stripped
Tested locally
> fix(html.js): add link tags to allow list

- stories/02-configuration/05-Multisite-Support.stories.mdx
> docs(multisite.config.js): update docs to add page on multisite config

- packages/integrations/components/integrationsManager/componentMap.js
- packages/integrations/components/parsely/index.js
Supports https://github.com/alleyinteractive/wp-irving/pull/297
> LEDE-435: Introduce component for Parse.ly integration

- CONTRIBUTING.md
- packages/forms/utils/getEndpointUrl.js
- packages/integrations/sagas/picoSaga.js
- packages/tracking/package-lock.json
[LEDE-650](https://alleyinteractive.atlassian.net/browse/LEDE-650)
* Converts the remaining references to `process.env.API_ROOT_URL` to use the new helper function `getEnv()` for multisite (in particular in the Pico saga)
* Adds a `package-lock.json` for the tracking package
Tested locally
> Fix Pico/Coral bug for multisite

- .travis.yml
- bin/deploy.sh
IRV-901
Changes:
* Remove unnecessary `sudo` and `dist`
* Use `jobs` to conditionally only run tests on PRs and deploys on the main branch.
* Cache the `.npm` folder instead of `node_modules`
> Optimize Travis Builds

- packages/core/server/development.js
N/A
Address CORS issues encountered with hot module reloading during multisite local development
Tested locally in client project
> fix(development.js): update headers for local development

- packages/styled/config/webpack.config.js
[**IRV-917**](https://alleyinteractive.atlassian.net/browse/IRV-917)
* Modify webpack config for styled components to get stylelint working again
Tested on a client project
> Fix stylelint in styled components package

- irvingjs.com/package.json
None.
Update the IrvingJS.com deploy npm script to `deploy:production`, and added `deploy:staging`.
> ci(irvingjs.com): improve npm scripts for deploy IrvingJS

- irvingjs.com/_files/robots.liquid
- irvingjs.com/dist/index.html
- irvingjs.com/dist/robots.txt
Removes the Disallow from the robots.txt to make the site visible to search engines.
> Make site visible in robots.txt

- irvingjs.com/_data/config.js
- irvingjs.com/dist/index.html
This fixes the incorrect canonical value, which is set in the config.js file.
I can see in the dist folder that the canonical is now irvingjs.com
> Fix canonical URL for IrvingJS.com

- irvingjs.com/README.md
None
As titled
README preview looked good.
> Fix Eleventy link in README.md

- packages/core/package-lock.json
> fix(core): update package-lock.json following sanitize-html update

- .storybook/README.md
- irvingjs.com/README.md
None.
Update the IrvingJS.com readme with info about commands and environments.
Just docs.
> docs(irvingjs.com readme): add info about commands and instructions

- packages/integrations/sagas/picoSaga.js
See https://alleyinteractive.atlassian.net/browse/LEDE-678
Updates Pico signal data layer message to just pass payload.
> LEDE-678: Only pass payload, not whole object

- packages/core/bin/irving
- packages/core/cli/build.js
- packages/core/config/webpack.config.js
- packages/core/config/webpack/index.js
- packages/core/config/webpack/plugins.js
- packages/core/package-lock.json
- packages/core/package.json
[**IRV-961**](https://alleyinteractive.atlassian.net/browse/IRV-961)
* Add commander to better organize and manage Irving's core CLI as it grows (and probably the CLI package, when we create it)
* Add an `--analyze` flag for the build command that will apply BundleAnalyzerPlugin
tested locally
> Add bundle analyzer behind a cli flag, also add commander for core CLI

- stories/13-wordpress-components/post-meta.stories.mdx
None.
* Fix examples for the `irving/post-meta` component.
Just docs.
> Fix dashes to underlines

- packages/core/bin/irving
- packages/core/cli/index.js
- packages/core/config/html.js
- packages/core/config/webpack.config.js
- packages/core/config/webpack/plugins.js
- packages/core/config/webpack/rules.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/server/serverRenderer.js
- packages/core/server/utils/getTemplateVars.js
- packages/core/server/utils/getWebpackAssetTags.js
[**IRV-953**](https://alleyinteractive.atlassian.net/browse/IRV-953)
* Abstract a couple pieces of functionality and export them for use by projects (our instance of `MiniCSSExtractPlugin`, `createAssetTags`)
* Fix a couple eslint issues
* Pass site-specific env to template vars config function(s)
Tested in lede
> Add required functionality to support site-specific stylesheets

- packages/core/server/index.js
None.
Moves the redirect middleware to happen before the proxy middleware
> Rearrange middleware

- packages/core/cli/index.js
This fixes a bug introduced in 7e27c211 which removed the action for the link-all command.
> fix(cli): fix link-all command

- packages/integrations/components/coral/index.js
This backports #457 to the 5.4 branch.
This fixes an issue where Coral is failing to decode JWT payloads when the payload includes URL
encoded versions of base64 encoded strings by splitting the JWT token and string replacing URL
encoded characters of the payload with the base64 alternatives.
LEDE-945
> fix(integrations): fix Coral login error when JWT fails

- package.json
- packages/core/config/webpack/rules.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/styled/package-lock.json
- packages/styled/package.json
https://alleyinteractive.atlassian.net/browse/IRV-982
* excludes `.mjs` files from file-loader
* fixes the `develop:prepare` script
* updates lodash to `4.17.20`
multiple people tested it locally.
> fix(sanitize): add mjs extension to file-loader excludes

- packages/styled-components/components/text/index.js
- packages/styled-components/package-lock.json
- packages/styled-components/package.json
[**IRV-922**](https://alleyinteractive.atlassian.net/browse/LEDE-922)
* Add `nowrap` prop to text component
* Render `nowrap` html content via `react-html-parser`
Tested on client project locally.
> add `nowrap` prop to text component to prevent rendering outer div

- packages/core/config/webpack/optimization.js
- packages/core/config/webpack/rules.js
- packages/core/server/utils/getWebpackAssetTags.js
N/A
* Support sass extension as an exclude for file-loader
* Add dev runtime chunk
Tested locally on client project.
> Fix hot loading with mini-css-extract-plugin

- stories/04-components/00-Overview.stories.mdx
- stories/04-components/07-Component-Tracking.stories.mdx
> LEDE-834: Expand docs for tracking integration

- packages/core/server/serverRenderer.js
- packages/core/server/utils/getTemplateVars.js
N/A
* Fix for site-specific head config to allow all fields to be merged in completely with other configs.
tested locally
> Merge site-specific head fully into other head configs

- packages/core/package-lock.json
- packages/core/package.json
N/A
Updates the `url-parse` package, see https://github.com/unshiftio/url-parse/pull/201
Tested locally, also will test on lede devleop.
> update url-parse package to fix bug in version 1.5.0

- packages/core/components/defaultErrorMessage/index.js
- packages/core/server/serverRenderer.js
- packages/core/server/views/error.ejs
- packages/core/services/fetchComponents.js
Improved error logging for JSON issues and visibility.
None.
* Log errors when the components API returns invalid JSON.
* Display errors on the frontend when `?debug` is present.
> feat(logging): improved error logging

- packages/core/cli/build.js
- packages/core/config/webpack/plugins.js
- packages/core/config/webpack/rules.js
[**IRV-997**](https://alleyinteractive.atlassian.net/browse/IRV-997)
* Fix a couple config bus
Tested locally
> fix a couple configs causing build errors

- packages/core/config/defaultCookies.js
- packages/core/services/fetchComponents.js
- packages/core/utils/endpoint/createEndpointUrl.js
- packages/core/utils/shouldAuthorize.js
[**IRV-800**](https://alleyinteractive.atlassian.net/browse/IRV-800)
* Update the cookie name from `authorizationBearerToken` to a more generic `authorizationToken`
* Switch to using basic auth to pass along token
Tested locally
> Updates related to integration of core Application Passwords

- packages/wordpress/components/adminBar/index.js
- packages/wordpress/package-lock.json
- packages/wordpress/package.json
LEDE-1452
Update the WP Admin Bar component to display children (allowing the backend to display an error message/warning), and sets an `irvingResetToken` flag cookie for the backend.
Tested locally and on develop/preprod environments.
> fix(wp admin bar): update the admin bar to display children, and set a flag for invalid tokens

- packages/core/server/serverRenderer.js
- packages/core/services/fetchComponents.js
- packages/core/services/logService/defaultService.js
- packages/core/services/logService/getService.js
- packages/core/services/logService/index.js
- packages/core/services/logService/logService.test.js
- packages/core/services/monitorService/defaultService.js
- packages/core/services/monitorService/getService.js
- packages/core/services/monitorService/index.js
- packages/core/services/monitorService/monitorService.test.js
- packages/vip-go/package-lock.json
- packages/vip-go/package.json
- packages/vip-go/services/logService.js
- packages/vip-go/services/monitorService.js
[**LEDE-1460**](https://alleyinteractive.atlassian.net/browse/LEDE-1460)
* Fix issue with incorrect log levels
* Create a more abstract method of getting the correct monitor or log service inside and outside the build
* Pass an actual `Error` instance to monitor service `logError` method when an error is logged
* Incorporate an optional Sentry transport into VIP Go logging
Tested locally
> Incorporate an optional Sentry transport into VIP Go logging service

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/services/fetchComponentData.test.js
- packages/core/services/fetchComponents.test.js
- packages/core/utils/isomorphicFetch.js
- packages/core/utils/isomorphicFetch.test.js
* https://alleyinteractive.atlassian.net/browse/LEDE-1519
* https://sentry.io/organizations/lede/issues/2393675828/events/7797282af5274614a1530575d4caf466/?project=5730320
* use `encodeURI` before passing a URL to `node-fetch`.
* Switch from `fetch-mock` to `fetch-mock-jest` for testing fetch-related funcitonality.
* add tests for `isomorphicFetch`
Tested locally
> Potentially address unescaped characters error

- packages/wordpress/config/aliases.js
na
Fixes empty theme during dev if npm linked to irving
Tested linked and unlinked.
> Add styled components alias for dev

- packages/core/components/app/index.jsx
- packages/core/components/defaultRouteInvalid/index.jsx
- packages/core/components/defaultRouteInvalid/readme.md
- packages/core/config/componentMap.js
- packages/core/reducers/defaultState.js
- packages/core/reducers/routeReducer.js
- packages/core/services/fetchComponents.js
- packages/core/services/fetchComponents.test.js
IRV-1012
Prevents invalid fetch requests to the components endpoint in the event that `API_ROOT_URL` is undefined.
[Updated the fetchComponets.test.js.](https://github.com/alleyinteractive/irving/pull/546/files#diff-4feb3f0253d52995ee0e99434be85bea4499b32b531603a8b670c65efd1026a7R28)
> Hotfix/irv 1012/multisite config 404

- packages/core/server/purgeCache.js
https://alleyinteractive.atlassian.net/browse/LEDE-1622
* Remove `return next()` from end of `purgeCache` middleware.
tested locally
> Remove call to next() which is causing response to end before write is finished

- packages/core/services/fetchComponents.js
> add IRVING_RENDER_ERRORS check

- packages/core/services/fetchComponents.js
> remove temp IRVING_RENDER_ERRORS

- packages/core/package-lock.json
- packages/styled/package-lock.json
> update package locks for styled and core

- packages/core/services/fetchComponents.js
Send response, request URL and status to Sentry when `response.json()` fails.
> feat(sentry): send response, request url and status to sentry 

- bin/release-cleanup
N/A
Modify the release cleanup script to pull the latest from `main` as well as provide slightly clearer instructions
> chore(release-cleanup): modify release cleanup script

- docs/package-lock.json
- docs/package.json
- docs/stories/03-features/Debugging.stories.mdx
> debug docs

- packages/vip-go/config/aliases.js
- packages/vip-go/config/getSentryConfig.js
- packages/vip-go/services/logService.js
> refactor(logging): refactor sentry config to match client/server

- packages/vip-go/services/logService.js
Adds a debug logger to Sentry Init config.
> feat(logging): log sentry init config

- packages/vip-go/services/logService.js
> Refactor logging logic

- packages/integrations/components/pico/index.jsx
Wait for pico instance before calling `getInstance()`.
> fix(pico): fix local storage is not available
