- components/image/image.js
If we have a caption we should use `<figure>`, otherwise `<Fragment>`, not the reverse.
> Fix reversed image WrapperElement logic

- packages/core/config/webpack/rules.js
These packages, which are included in Irving core, contain arrow functions, which must be transpiled with babel to avoid cross browser issues.
ticket: https://alleyinteractive.atlassian.net/browse/IRV-255
> IRV-255 Add specific packages to the `includes` variable in webpack rules config

- packages/core/services/fetchComponents.js
This makes the URL more readable and aids in ensuring the URL purged by Varnish on VIP Go exactly matches the URL requested by Irving (in order to properly bust the cache when a post is updated)
> Do not encode query string

- packages/core/config/webpack/rules.js
This update adds `publicPath: '/'` to the url-loader config options, which fixes an issue with loading static assets in CSS with `url()`.
> Add publicPath: '/' to url-loader config

- packages/core/config/webpack.config.js
- packages/core/config/webpack/rules.js
* Modify symlink behavior for local dev
* Move the block that picks out the node modules with arrow functions from the main test down to the `babel-loader` section, so that those 3 node modules _do_ get transpiled by Babel, but _do not_ get linted
> Modifications to get npm link working locally

- packages/vip-go/irving.config.js
These weren't being referenced/used in every place they need to be.
> Add cache, log, monitor services to irving.config.js

- packages/integrations/components/googleTagManager/index.js
After thinking this through a bit more with @ostowe , we decided that 
- The `useLoadScript` hook wasn't necessary to prevent the duplicate script tag issue. The same can be achieved by just adding the script tag to the helmet component separately.
- It may be best to ensure that the `gtm.start` object is only added to the data layer once, rather that on each re-render of the component.
> IRV-294 Remove useLoadScript hook, ensure gtm.start fires once

- package-lock.json
- packages/audio-player/package-lock.json
- packages/babel-preset-irving/index.js
- packages/core/config/webpack/entry.js
- packages/core/config/webpack/rules.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/utils/getConfigField.js
- packages/core/utils/isomorphicFetch.js
- packages/forms/package-lock.json
- packages/integrations/package-lock.json
- packages/postcss/package-lock.json
- packages/styled/package-lock.json
- packages/styleguide/package-lock.json
- packages/vip-go/package-lock.json
This PR will:
- Move `chalk` to only be imported in a node environment
- Use `whatwg-fetch` polyfill in browser, `node-fetch` in node
- Add a few more node modules to the list of those that need to be transpiled for IE11
- Add `useBuiltins: 'usage'` to babel config to, hopefully, reduce the number of polyfills we're using to only those we need.
> Ie11 bugfixes

- packages/babel-preset-irving/index.js
'unambiguous' setting will allow mixing CommonJS and es modules. no clue why babel hasn't complained about this before.
> Add sourceType to babel config

- packages/styled/utils/cssGrid.js
This addresses a couple of issues that came up in IE11 debugging:
- The complex nested `calc()` expressions were not working properly, so I moved those calculations out into JS.
- We needed a `flex-wrap: wrap` style.
- `max-width` seems to work better than `width`.
- We needed to add some bottom padding to mimic the grid gap styles on layouts with wrapping elements.
> Bug - update cssGrid columnSpan flexbox fallbacks

- packages/styled/components/grid/container.js
- packages/styled/utils/cssGrid.js
This update fixes a couple of things missed in the last PR (#158):
- In some cases and for reasons I still don't understand, the flexbox width values calculated in the `columnSpan` function were negative.
- I also added some more explicit checking to that the width calculations only work for numbers and arrays, to reduce the possibility of errors.
- Child `GridCell` components were not receiving `gridColumns` values set on the parent as expected, but only ever getting the value set in the top level GridContext provider.
> Bug - grid fallbacks columns calculation

- packages/styled/utils/cssGrid.js
This fixes an issue with the previous styled package release, where using `.reverse()` unintentionally mutated the `columns` array in the `columnSpan` helper function.
> styled package - cssGrid helpers: Ensure columns array is not mutated

- packages/core/components/helpers/defaultLoading/defaultLoading.css
- packages/core/components/helpers/defaultLoading/index.js
- packages/core/components/hoc/withAsync.js
- packages/core/components/hoc/withLoader.js
- packages/core/components/readme.md
N/A
- switch to using children for default loading component content
- add className prop to default loading component
- tweak styles for default loading component
- add option to override default loading component entirely in withLoader
Tested in client project
> Update features for default loading component

- packages/core/server/customizeRedirect.js
N/A
* Disable `express-naked-redirect` in development
* Update `customizeRedirect` option to be a function returning an object.
tested locally
> Don't run express-naked-redirect in development

- packages/core/config/webpack/output.js
Rename jsonp function to prevent conflicts with other webpack bundles
IRV-526
Use `irvingWebpackJsonp` as the `jsonpFunction` name for client builds. This will prevent conflicts with other libraries/packages using the default value.
> Rename jsonp function to prevent conflicts

- packages/integrations/components/coral/commentCount.js
DEF-111
Adds:
* CommentCount component inside the Coral integrations folder for displaying comment counts of an article from Coral.
This can be tested along with https://github.com/alleyinteractive/wp-irving/pull/232 or manually, by hard coding a component response in a layout file that passes the following values:
* `articleUrl` – The URL of an article.
* `embedUrl` – The URL to a Coral instance.
* `noText` – Boolean (optional), whether to hide the text and just show the number of comments.
> Add Coral Comment Count component

- packages/core/server/purgeCache.js
- packages/vip-go/services/cacheClient.js
[**IRV-639**](https://alleyinteractive.atlassian.net/browse/IRV-639)
* Return core `defaultClient` from vip-go `cacheClient` function instead of `defaultService`
* Add an additional safety check for the `cacheService.client.pipeline` just in case the client is not `null` as it should be when redis isn't configured.
Tested on client project
> Fix bug with cacheClient when redis not configured

- packages/integrations/components/coral/commentCount.js
This fixes an issue where the Coral comment count function was not being fired on client side page
loads.
> fix(Coral): Fix client rendering activation of comment counts

- packages/styled-components/components/byline/index.js
N/A
Remove the `<span>` that exists only in the markup for the case of 2 children, which is inconsistent from the markup produced by the other cases (1 child, 3+ children)
Tested locally
> fix(byline): remove errant span tag in component with 2 children

- packages/core/server/purgeCache.js
N/A
* Remove `res.end()` call which was being called too early and therefore resulting in the following error:
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
```
(which in practice was causing the Redis cache to not clear)
Tested locally
> fix(purgecache): remove duplicative res.end()

- packages/core/components/app/index.js
- packages/core/components/root/index.js
- packages/core/config/html.js
* Split up app component and component responsible for rendering connected roots to prevent unnecessary rerenders.
* Add `h1` and `time` tags to html `allowedTags` because gutenberg supports them.
Tested in client project.
> Separate component responsible for rendering roots from app wrapper

- packages/wp-admin-bar/components/adminBar/index.js
N/A
Fixes the following warning:
```
React has detected a change in the order of Hooks called by AdminBar.
```
This error was happening because the `useEffect` hook was not present for all renders
Tested locally
> fix(adminbar): fix React error regarding a change in the order of hooks

- packages/integrations/components/integrationsManager/index.js
- packages/integrations/components/integrationsManager/integrationsManager.test.js
This removes the mechanism that caches integrations data to the Redux store, and instead prefers to
re-render fresh integration data each time the integrations manger is rendered and recieves updates
integration data. This fixes an issue where fresh data being passed from API responses were not
being passed as props to components during page renders.
After applying this change, you can see that the GTM integration and Pico integration is rendering with fresh data from the components API response.
> fix(integrationsManager): Remove Redux caching of integrations data

- packages/core/server/utils/getTemplateVars.js
[**IRV-673**](https://alleyinteractive.atlassian.net/browse/IRV-673)
* Move logic for collecting and rendering `head` variables to happen after `renderToString()` occurs.
Tested on client project.
> Collect and render head vars after renterToString is called

- packages/styled-components/components/socialSharing/index.js
N/A
This change will provide a little more flexibility for defining properties of individual social share platforms, e.g. setting the `target` per platform. It could also be extended more easily later to allow defining of the icon name, icon title, etc.
Tested locally
> feat(socialsharing): update Social Sharing component to allow more flexibility

- packages/styled-components/components/link/index.js
https://alleyinteractive.atlassian.net/browse/DISCO-69
Add an optional `aria-hidden` attribute to the Link component, which takes its value from an optional `ariaHidden` prop. The default value of the `ariaHidden` prop is `null`, so that if no `ariaHidden` prop is passed to the Link component, the `aria-hidden` attribute will not appear on the rendered `<a>` element.
The motivation behind this was to provide a way to hide links that do not contain descriptive text, and should not be read by a screen reader. In this specific case, during work on an accessibility audit for site that's using Irving, an issue with the Byline component came up: the author avatar and author name are separate links, and the avatar link contains only an image. 
Accessibility requirements dictate that links should …
> DISCO-69 Add optional aria-hidden attribute and prop to Link component

- packages/integrations/components/pico/index.js
- packages/integrations/sagas/picoSaga.js
IRV-710
This fixes a bug where pre-fetched pages were not triggering Pico actions
because the Pico component was being rendered from the previous page's
state. We had previously included a check for whether we had already
dispatched a Pico page update using a `useState` hook to bypass duplicate
dispatches and that state was not being reset between pageviews if the Pico
component instance was being reused.
This refactors the logic for side effects into several separate `useEffect`
hooks to separate responsibilities for each side effect and simplify the
number of dependencies each `useEffect` checks before running.
> fix(pico): Trigger Pico actions on pre-fetched pages

- packages/integrations/components/pico/index.js
- packages/integrations/components/pico/utils.js
This fixes a bug introduced in b590767 that caused Pico not to fire the initial page visit for the
initial pageview.
See: IRV-710
> fix(Pico): ensure Pico loads on first page render

- packages/integrations/components/pico/index.js
This changes the order of the initial dispatched actions after the Pico notes are mounted in ordre
to try and fix a race condition where the first payload to Pico is being fired too early.
IRV-710
> fix(pico): Fix timing bug with firing the initial Pico action

- packages/integrations/components/pico/index.js
This PR fixes an issue where the Pico `pageInfo` would not be updated when navigating through article pages and viewing the same article more than once. This is done by removing an extraneous call to `dispatchPicoPageInfo` that was causing the action to be fired twice on an initial server render and adding the current URL as a dependency to the mount effect hook.
> IRV-710: Fix Pico load states

- packages/styled-components/components/link/index.js
Spreading `{...props}` into the link wrapper caused the `theme` prop in the `LinkWrapper` styled component to be overridden, causing `siteTheme` to break. This PR will fix this issue.
Tested in client projects.
> Fix issue with spreading props into link wrapper component

- packages/integrations/components/coral/withPico.js
- packages/integrations/components/pico/index.js
- packages/integrations/package-lock.json
This PR re-introduces a state variable, `canComment`, into the withPico HOC wrapper for Coral. Additionally, it adds the Irving log service to track the component's lifecycle for easier debugging.
The issue this corrects was due to the fact that there were instances where even when component variables pulled from the Redux store would update, this would not trigger the wrapper to re-render. This caused an issue where even though users would have a valid Pico payment tier and would have received a JWT token to log the user into the embed via SSO, the unauthenticated embed instance would persist in the DOM leaving the user logged out.
This behavior is corrected by the aforementioned state variable and a `useEffect` hook that uses the variables derived from the Pico signal, the Coral JWT …
> fix(coral): Enforce component re-renders on selector variable changes

- packages/integrations/components/coral/index.js
Noticed because of multiple GTM events firing as pageviews accumulated. Uses `useHook` cleanup to remove embeds.
> HOTFIX: Remove Coral embeds to prevent side effect buildup

- packages/core/config/html.js
https://alleyinteractive.atlassian.net/browse/LEDE-566
Add `sub` and `sup` to the list of allowed richText tags in html.js.
> fix(html.js): adds sub and sup to allowed html tags

- packages/styled-components/componentMap.js
No ticket.
Fix a bug with `createThemedComponentMap` where component themes in the `@irvingjs/styled-components` package weren't being included unless a custom theme was being set.
> Fix styled components component map logic

- packages/styled-components/components/text/themes/html.js
None.
Add a `height: auto;` property to the `irving/text` `html` theme, preventing images from being distorted.
Without `height: auto;`,
Including `height: auto;`,
> Update `html` theme on `irving/text` to not distort images

- packages/core/config/paths.js
- packages/core/config/webpack/alias.js
- packages/loadable/server/getAppTemplateVars.js
- packages/styled-components/components/byline/themes/default.js
- packages/styled/config/stylelint.config.js
- packages/wordpress/components/blockStyles/blocks/heading.js
- packages/wordpress/components/blockStyles/blocks/image.js
- packages/wordpress/components/blockStyles/blocks/index.js
- packages/wordpress/components/blockStyles/blocks/latestPosts.js
- packages/wordpress/components/blockStyles/blocks/list.js
- packages/wordpress/components/blockStyles/blocks/mediaText.js
- packages/wordpress/components/blockStyles/blocks/paragraph.js
- packages/wordpress/components/blockStyles/blocks/pullquote.js
- packages/wordpress/components/blockStyles/blocks/quote.js
- packages/wordpress/components/blockStyles/blocks/separator.js
- packages/wordpress/components/blockStyles/blocks/table.js
- packages/wordpress/components/blockStyles/blocks/utils/link.js
- packages/wordpress/components/blockStyles/blocks/video.js
[**LEDE-528**](https://alleyinteractive.atlassian.net/browse/LEDE-528)
* Switch all async chunks to using a `rel="prefetch"` link instead of `rel="preload"`. Still not 100% sure why this is necessary, but it seems to resolve the issue.
* Tested on client project
> fix(loadable): use prefetch instead of preload for async chunks

- packages/core/package.json
The latest release of sanitize-html is a much smaller package size, and should improve performance
overall.
We were previously using versions ^1.23.0, which was 1.62 MB unpacked. Version 2.3.0 is reported as being 67.2 kB since they removed built files (including polyfills) in version 2.0.
> perf(core): Upgrade sanitize-html to 2.3.0

- packages/core/utils/children.js
- packages/core/utils/children.test.js
This utility returns an object where the components are mapped by the group prop/config value.
https://alleyinteractive.atlassian.net/browse/IRV-726
Add a utility which maps an array of children into an object using each child's `group` prop.
```
const components = [
{
name: "irving/example-a",
config: {
"group": "first",
},
},
{
name: "irving/example-b",
config: {
"group": "first",
},
},
{
name: "irving/example-c",
config: {
"group": "second",
},
},
{
name: "irving/example-d",
},
];
const groups = groupChildren(components);
console.log(groups);
```
Output:
```
{
first: [
{
name: "irving/example-a",
config: {
"group": "first",
},
},
{
name: "irving/example-b",
config: {
"group": "first",
},
},
],
second: [
{
name: "irving/example-c",
config: {
"group": "second",
},
},
],
rest: [
{
name: …
```
> feat(groupchildren utility): adds a groupChildren uility to core

- packages/core/server/utils/getWebpackAssetTags.js
N/A
* Webpack runtime was failing to load when loadable package wasn't installed. This PR will fix that issue.
tested locally, will test in develop
> Fix runtime loading without loadable

- packages/integrations/components/pico/index.js
LEDE-843
This checks the status of the `loading` state in Redux, using the `useLoading()` hook before firing
off `UPDATE_PICO_PAGE_INFO` actions to ensure components are rendered for Pico to respond to.
Otherwise a race condition will block Pico from loading when a visitor is logged into the back end.
> fix(pico): only update Pico page info after authorized requests finish

- packages/integrations/components/coral/index.js
LEDE-945
This fixes an issue where Coral is failing to decode JWT payloads when the payload includes URL
encoded versions of base64 encoded strings by splitting the JWT token and string replacing URL
encoded characters of the payload with the base64 alternatives.
Have tested this flow locally against the Coral integration.
> fix(integrations): fix Coral login error when JWT fails

- packages/core/config/webpack/plugins.js
- packages/styled-components/componentMap.js
- packages/styled-components/components/bodyWrapper/index.js
- packages/styled-components/components/loader/defaultLoading.js
- packages/styled-components/components/loader/index.js
- packages/styled-components/components/loader/themes/default.js
- packages/styled/components/hoc/withThemes.js
- packages/styled/types/propTypes.js
[**LEDE-1187**](https://alleyinteractive.atlassian.net/browse/LEDE-1187)
* Add the loader component to the component map.
* Deprecate/remove the `fullScreen` and `fullScreenBgColor` options for the loader component as they are too prescriptive and difficult to override. We can add it back in later as a theme, if necessary.
* Allow a theme for the `BodyWrapper` component to cascade down and theme the `Loader` and `DefaultLoader` components as well.
* Add functionality to `withThemes` to allow passing in a theme directly to a component as a prop. This prop theme will take precedence over a `themeName`.
Tested locally on client projects
> Fix body wrapper and loader components so they're actually configurable

- packages/integrations/components/pico/index.js
- packages/integrations/reducers/defaultState.js
- packages/integrations/reducers/picoReducer.js
- packages/integrations/selectors/picoSelector.js
N/A
* Add a flag in pico redux state to say if a call to `pico('visit')` has been made since the last navigation. This should prevent duplicate visits.
* Remove lingering outdated state values.
I've tested locally.
> Add visited flag in redux to prevent multiple visit calls on a single navigation

- packages/babel-preset-irving/index.js
- packages/babel-preset-irving/package-lock.json
- packages/babel-preset-irving/package.json
- packages/core/package-lock.json
- packages/core/package.json
[**IRV-960**](https://alleyinteractive.atlassian.net/browse/IRV-960)
* Fix issue with duplicate core-js polyfills showing up in irving bundles.
* Include only polyfills that don't pollute the global scope via `@babel/plugin-transform-runtime`
* Include syntax transformations via `@babel/preset-env`
Tested locally, will test again with alpha release.
> Fix duplicate instances of core-js showing up in irving bundles.

- packages/wordpress/config/webpack.config.multi.js
N/A
* Prevents clean webpack plugin from removing built assets from the block editor build
tested locally
> Fix issue with blockEditor build assets being removed

- packages/core/sagas/resolveComponents.js
N/A
Should fix the following server-side error seen in newrelic: `Cannot set property location of#<Window> which has only a getter`
Tested locally, will test on develop/preprod
> return early from components saga if we aren't redirecting

- packages/core/utils/isomorphicFetch.js
https://alleyinteractive.atlassian.net/browse/LEDE-1516, maybe https://alleyinteractive.atlassian.net/browse/LEDE-1519 also
* Use the `url-parse` package to check for a protocol instead of the current less-reliable regex test
Tested locally with the URL seemingly causing the issue in sentry.
> attempt to address issue with fetch called using URL without protocol

- packages/core/sagas/index.js
- packages/core/sagas/resolveComponents.js
- packages/core/sagas/waitToScroll.js
- packages/core/selectors/getRouteMeta.js
https://alleyinteractive.atlassian.net/browse/LEDE-1332 I guess
* Ensure hash is available, even on SSR
* set up `waitToScroll` saga on `FINISH_LOADING` and `RECEIVE_COMPONENTS` instead of `LOCATION_CHANGE` and set it up before auth request to ensure it's fired at the right times.
tested locally
> fix waitToScroll functionality to ensure it fires on server side loads

- packages/core/services/fetchComponents.test.js
- packages/integrations/components/coral/index.jsx
N/A
Pass the story ID (post ID) to the Coral embed. Explicitly providing a unique identifier should eliminate issues encountered when the URL of a post changes
Tested locally and will test in staging environment
> fix(coral): pass post ID to Coral embed

- packages/wordpress/config/proxyPassthrough.js
None
Allow the `*/embed/` route to work as expected in core WordPress by proxying it.
Tested and confirmed on a production project.
> Add /embed/* to the WordPress proxy config

- packages/styled-components/components/link/index.jsx
- Convert aria attributes to kebab case before spreading as camel case aria attributes are no supported.
- Add support for passing a tabindex prop.
> feat(a11ly): ➜ Pass aria atts and tabindex to link

- packages/vip-go/services/generateLogInfo.js
- packages/vip-go/services/logService.js
LEDE-1760
- Fixes a bug where context persists between errors logged to Sentry resulting in stale (or incorrect) tags.
- Adds support for passing `addtionalData` so larger amounts of data and non primitive data types can be sent to Sentry.
> Feature/lede 1760 - clear scope and add support for passing additionalData to Sentry

- packages/integrations/components/coral/commentCountStatic.jsx
N/A
* Add a new component that will render a static comment count passed to it (using markup that matches the output from the dynamic Coral comment count component)
Tested locally, and will test in preproduction environment.
> feat(commentcountstatic): add new Coral component for displaying static comment count data

- packages/integrations/components/coral/commentCountStatic.jsx
N/A
Add `articleUrl` and `noText` config to achieve full parity with the original Coral comment count component. Most notably, the `data-coral-url` attribute needs to be present, otherwise Coral assumes the canonical URL and live-updates all Coral comment counts on the page to the same comment count when a new comment is made.
Tested locally and in preproduction environment
> fix(commentcountstatic): add support for additional Coral config in static component

- packages/integrations/components/pico/usePicoGTMEvents.js
Pico sends a string back for event.type for every event except for pico.user.registered which it sends `{user: name@email.com}`  which would results in an action that is `[object, object]`.
This PR checks for that case and sends along a string as the event action.
> fix(analytics): fix [object object] ga event action

- packages/integrations/components/coral/commentCountStatic.jsx
N/A
Change the class name so that the 2 Coral comment count components are differentiated and the Coral embed does not override comment counts (`.coral-count` is a selector with significance for the embed)
tested locally
> fix(commentcountstatic): differentiate class name for secondary Coral comment count component

- docs/.storybook/babel.config.js
N/A
Add service aliases to storybook babel config via `core/config/irving/getServiceAliases`. This will prevent failed builds resulting from components using the tracking service, in particular.
tested locally
> add service aliases to docs babel config

- packages/integrations/components/pico/index.jsx
This PR makes sure the pico gadget script is loaded before calling `window.pico('visit', {...})`.
We were waiting on a number of conditions to dispatch a page visit (`dispatchUpdatePicoPageInfo`) one of which was `pico.scriptOnLoad`.  `pico.scriptOnLoad` is fired at the very beginning of the script and not after the script is loaded creating a brief race condition between the script loading and our action running.
> fix(pico): Patch race condition by making sure pico script is loaded before triggering visit

- packages/integrations/components/coral/index.jsx
N/A
Remove an earlier fix that converted the JWT token payload for Coral from base64url to base64. While this skirted the `atob()` error, it resulted in malformed tokens in some cases which would cause the Coral embed to die. The JWT spec calls for base64url, and Coral fixed the underlying issue in the Talk repo [here](https://github.com/coralproject/talk/pull/3206). Note that this requires you be on 6.3.7 or later of Coral for compatibility. 
Tested locally and in develop environments
> fix(coral): remove base64url encoding to base64 encoding conversion on Coral JWT token

- packages/integrations/components/pico/index.jsx
https://alleyinteractive.atlassian.net/browse/LEDE-1924
* Rework code intended to prevent pico's `'Local storage not available'` error message to use the Pico lifecycle value instead of accessing the global `Pico` object directly.
* hoping this works better as it avoids calling `window.Pico.getInstance()` which, if called too early, seems to throw that local storage error.
* Tested locally (so far)
> fix scriptLoaded flag to use pico lifecycle instead of accessing Pico object directly

- packages/storybook/babel.config.js
N/A
* Fix storybook builds to include service aliases (which, when missing, will break storybook for any component utilizing components in the `styled-components` package)
TEsted locally
> Add service aliases to storybook babel config
